version: "3"
services:
  app:
    build:
      context: ./
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
